### ISSUE TITLE
Parsing test of traceswo response incorrect

### ISSUE THREAD

**Issue by sidprice** [compuphase/Black-Magic-Probe-Book#14]
The following line is incorrect in bmp-support.c:

ok = ((ptr = strchr(buffer, ':')) != NULL && strtol(ptr + 1, &ptr, 16) != 5 && *ptr == ':');

It should be:

ok = ((ptr = strchr(buffer, ':')) != NULL && strtol(ptr + 1, &ptr, 16) == 5 && *ptr == ':');

**Comment by compuphase** [comment]
Oops... Thanks. Fix commited in 7963c08b55b54aa0bd0a876f57320aad4a7d4dd2.
