### ISSUE TITLE
Windows: Console window stays open for a long time after closing BMTrace

### ISSUE THREAD

**Issue by sidprice** [compuphase/Black-Magic-Probe-Book#18]

**Comment by compuphase** [comment]
The console window should not be there in the first place. These are GUI applications. However, the linker sets a flag in the PE header that it is a console application.
Are you using Makefile.mingw? I will need to look at the linker options.

**Comment by sidprice** [comment]
Yes, I am using Makefile.mingw

**Comment by compuphase** [comment]
Commit a2142e835245827057b1a12c6797ee9f0fe2f86f has an extra linker flag for MingW to avoid a console window on GUIs.

**Comment by sidprice** [comment]
@compuphase Thank you, looks good and BMTrace shuts down much more quickly without the console window.
