### ISSUE TITLE
Problems with make - Windows

### ISSUE THREAD

**Issue by sidprice** [compuphase/Black-Magic-Probe-Book#23]
It seems the Makefile.mingw has spaces before some commands and make requires TABs:

Makefile.mingw:65: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.

**Comment by sidprice** [comment]
I will generate a PR if you like.

**Comment by sidprice** [comment]
It also appears that the Windows Sockets library (ws2_32) is required by the linker commands.

**Comment by sidprice** [comment]
Seems I can't make a new PR for some reason

**Comment by compuphase** [comment]
I merged the pull request. Thanks.
