### ISSUE TITLE
Incorrect shell syntax for Linux

### ISSUE THREAD

**Issue by whitelynx** [compuphase/Black-Magic-Probe-Book#27]
On page 78, there is a sample command for Linux:
```
arm-none-eabi-gdb -nx --batch \
-ex 'target extended-remote `bmscan gdbserver`' \
-ex 'monitor swdp_scan' \
-ex 'attach 1' \
-ex 'load' \
-ex 'compare-sections' \
-ex 'kill' \
blinky.elf
```

On the second line, the backticks will not function because they're inside a single-quoted string. To fix this, the line should read:
```
-ex "target extended-remote `bmscan gdbserver`" \
```

**Comment by compuphase** [comment]
Thank you for spotting this and reporting it. I have commited a fix (commit 1b93b2ebb1e48dd3914dc1c7d70c383d7d76f819).
