### ISSUE TITLE
Build error on Ubuntu Linux 18.04

### ISSUE THREAD

**Issue by simonsunnyboy** [compuphase/Black-Magic-Probe-Book#28]
The build starts correctly with the following command line from the source directory:

`make -f ./Makefile.linux GLFW_LIBNAME=glfw`

However building of bmserial leads to the following error message:

`bmserial.c:71:11: fatal error: res/icon_serial_64.h: Datei oder Verzeichnis nicht gefunden`

The folder source/res/ indeed does not contain the header file.

**Comment by compuphase** [comment]
Fixed in commit a9ca67d3c74630b520fc49fa22752800f70123df.
Thank you for reporting.

**Comment by simonsunnyboy** [comment]
I can confirm all sources now build fine after the update.
