### ISSUE TITLE
bmflash as a generic programming tool

### ISSUE THREAD

**Issue by simonsunnyboy** [compuphase/Black-Magic-Probe-Book#30]
The bmflash tool only supports .elf files if I understand correctly.
It would be great to be able to also select arbitrary .bin or .hex files for flashing to allow universal use with existing binaries.

**Comment by compuphase** [comment]
Implemented in commit ccc75fe7427b48f7f3130718914d19ee78e7c10b.
ELF is still the recommended format, because the utility can do some checks on an ELF file prior to downloading it.
