### ISSUE TITLE
bmscan fails if multiple BMPs have been connected

### ISSUE THREAD

**Issue by sidprice** [compuphase/Black-Magic-Probe-Book#4]
I have more than one BMP, plus my own ctxLink probe which is based upon BMP.

The find_bmp method appears to only search for "interface" "0", here is a snapshot of the registry on my PC.

![BMP_Reg_1](https://user-images.githubusercontent.com/12300040/66275617-a9c39500-e847-11e9-84be-37533b046008.PNG)

**Comment by sidprice** [comment]
Sorry, I misunderstood the "interface", I need to dig deeper to find why the BMP is not being found.

**Comment by sidprice** [comment]
I believe the issue is that the code is assuming there is only a single entry under "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Enum\USB\VID_1D50&PID_6018&MI_00", when in fact on my system, because I have multiple BMPs and ctxLinks that have been attached I have five devices. The first device entry tested is not the one currently connected and so the find fails.

**Comment by sidprice** [comment]
I think I have fixed this issue with this [PR](https://github.com/compuphase/Black-Magic-Probe-Book/pull/5).

Only able to test using Windows.

**Comment by compuphase** [comment]
Commit d228b6c31ede07c3049671f317bb15d6dc7f3210 fixes this issue (tested under Microsoft Windows and Linux).
