### ISSUE TITLE
Building on Debian 10

### ISSUE THREAD

**Issue by riktw** [compuphase/Black-Magic-Probe-Book#9]
Hello,

First of all, thanks for the amazing book and tools in here.

When building the tools on Debian 10, I ran across a few issues:
I needed libbsd-dev as well as the other listed requirements.
I had to remove and regenerate makefile.dep as it contained references to bmscan.h that does not exist as far as I can tell.
I had to change -lglfw3 to -lglfw in the Makefile.linux, but I think this can be different per distro. 

I hope this feedback is useful :)

Regards, Rik

**Comment by compuphase** [comment]
libbsd-dev is now listed as a requirement.

makefile.dep is fixed in commit 9990b9aeca093839b915cdf92efd150188f7d361.

I also changed Makefile.linx so that the library name for GLFW may be set in makefile.cfg. The default is still "glfw3".

Thank you for your comments.
